version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: db_init
    depends_on:
      postgres:
        condition: service_started
        restart: true
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./data:/data
      - ./logs:/logs
      - /Users/vitaly/soccerdata:/soccerdata
    networks:
      - app-network
  
  streamlit:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: streamlit
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_started
        restart: true
      db:
        condition: service_started
        restart: true
    volumes:
      - ./logs:/logs
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge